### ISSUE TITLE
Error, environment was found but could not be launched

### ISSUE THREAD

**Issue by pengtengupup** [wuyike2000/MLDT#1]
Hello, when i try to  run ```bash scripts/llm_collection.sh``` to generate the training corpus for "MLDT"， i got the error ：

Traceback (most recent call last):
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/llm_collection.py", line 57, in <module>
    main()
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/llm_collection.py", line 53, in main
    vh_envs = utils_interactive_eval.connect_env(args, logging) # 连接仿真
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/utils_bc/utils_interactive_eval.py", line 34, in connect_env
    vh_envs = UnityEnvironment(num_agents=args.n_agent,
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/envs/unity_environment.py", line 93, in __init__
    self.comm = comm_unity.UnityCommunication(port=str(self.base_port), **executable_args) # 启动仿真报错
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/../virtualhome/simulation/unity_simulator/comm_unity.py", line 44, in __init__
    self.launcher = communication.UnityLauncher(port=port, file_name=file_name, x_display=x_display,
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/../virtualhome/simulation/unity_simulator/communication.py", line 15, in __init__
    self.launch_executable(file_name, x_display=x_display, no_graphics=no_graphics, logging=logging, docker_enabled=docker_enabled)
  File "/share/home/202320143457/guopt/MLDT/MLDT/task-planning/../virtualhome/simulation/unity_simulator/communication.py", line 181, in launch_executable
    raise Exception('Error, environment was found but could not be launched')
Exception: Error, environment was found but could not be launched
What is the problem here?

**Comment by wuyike2000** [comment]
What is your environment?

**Comment by wbl66** [comment]
I met the same error.Has the problem been resolved？

**Comment by wuyike2000** [comment]
It may be an environmental issue. Please configure the environment according to the instructions provided in the README.md.
